#
# Technoplatz BI
#
# Copyright (C) 2019-2023 Technoplatz IT Solutions GmbH, Mustafa Mat
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses.
#
# If your software can interact with users remotely through a computer
# network, you should also make sure that it provides a way for users to
# get its source.  For example, if your program is a web application, its
# interface could display a "Source" link that leads users to an archive
# of the code.  There are many ways you could offer source, and different
# solutions will be better for different programs; see section 13 for the
# specific requirements.
#
# You should also get your employer (if you work as a programmer) or school,
# if any, to sign a "copyright disclaimer" for the program, if necessary.
# For more information on this, and how to apply and follow the GNU AGPL, see
# https://www.gnu.org/licenses.
#

version: "3.9"
services:
  edoksis:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${HUB}/technoplatz/bi-intg-edoksis:${VERSION}
    container_name: edoksis
    hostname: edoksis
    restart: always
    volumes:
      - bi-cert-volume:/cert
      - bi-storage-volume:/docs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${EDOKSIS_PORT}:80"
    environment:
      - MONGO_DB=${MONGO_DB}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - MONGO_HOST0=${MONGO_HOST0}
      - MONGO_HOST1=${MONGO_HOST1}
      - MONGO_HOST2=${MONGO_HOST2}
      - MONGO_PORT0=${MONGO_PORT0}
      - MONGO_PORT1=${MONGO_PORT1}
      - MONGO_PORT2=${MONGO_PORT2}
      - MONGO_RS=${MONGO_RS}
      - MONGO_TLS=${MONGO_TLS}
      - MONGO_TLS_CA_KEYFILE=${MONGO_TLS_CA_KEYFILE}
      - MONGO_TLS_CERT_KEYFILE=${MONGO_TLS_CERT_KEYFILE}
      - MONGO_TLS_ALLOW_INVALID_CERTIFICATES=${MONGO_TLS_ALLOW_INVALID_CERTIFICATES}
      - MONGO_RETRY_WRITES=${MONGO_RETRY_WRITES}
      - EDOKSIS_USER=${EDOKSIS_USER}
      - EDOKSIS_PASSWORD=${EDOKSIS_PASSWORD}
      - EDOKSIS_VKN=${EDOKSIS_VKN}
      - EDOKSIS_URL=${EDOKSIS_URL}
      - EDOKSIS_TIMEOUT_SECONDS=${EDOKSIS_TIMEOUT_SECONDS}
      - CUSTOMIZATION_ID=${CUSTOMIZATION_ID}
      - UBL_VERSION_ID=${UBL_VERSION_ID}
      - ADVICE_TYPE_CODE=${ADVICE_TYPE_CODE}
      - IDENTIFICATION_SCHEME=${IDENTIFICATION_SCHEME}
      - PROFILE_ID=${PROFILE_ID}
      - SUPPLIER_NAME=${SUPPLIER_NAME}
      - SUPPLIER_STREET_NAME=${SUPPLIER_STREET_NAME}
      - SUPPLIER_BUILDING_NUMBER=${SUPPLIER_BUILDING_NUMBER}
      - SUPPLIER_CITY_NAME=${SUPPLIER_CITY_NAME}
      - SUPPLIER_PROVINCE_NAME=${SUPPLIER_PROVINCE_NAME}
      - SUPPLIER_COUNTRY_NAME=${SUPPLIER_COUNTRY_NAME}
      - SUPPLIER_POSTAL_CODE=${SUPPLIER_POSTAL_CODE}
      - SUPPLIER_ADDRESS_ID=${SUPPLIER_ADDRESS_ID}
      - SUPPLIER_WEB_ADDRESS=${SUPPLIER_WEB_ADDRESS}
      - SUPPLIER_ALIAS=${SUPPLIER_ALIAS}
      - SUPPLIER_PHONE=${SUPPLIER_PHONE}
      - SUPPLIER_FAX=${SUPPLIER_FAX}
      - SUPPLIER_EMAIL=${SUPPLIER_EMAIL}
      - SUPPLIER_TAX_OFFICE=${SUPPLIER_TAX_OFFICE}
      - SUPPLIER_TAX_NO=${SUPPLIER_TAX_NO}
    env_file:
      - .env
    secrets:
      - mongo_username
      - mongo_password
      - mongo_tls_keyfile_password
    extra_hosts:
      - mongo0:${SUBNET_MONGO0_IPV4}
      - mongo1:${SUBNET_MONGO1_IPV4}
      - mongo2:${SUBNET_MONGO2_IPV4}
    networks:
      network0:
        ipv4_address: ${SUBNET_EDOKSIS_IPV4}

volumes:
  bi-cert-volume:
    name: bi-cert-volume
    external: true
  bi-storage-volume:
    name: bi-storage-volume
    external: true

networks:
  network0:
    name: network0
    external: true
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

secrets:
  mongo_initdb_root_password:
    file: ./../../.mongo/mongo_initdb_root_password
  mongo_initdb_root_username:
    file: ./../../.mongo/mongo_initdb_root_username
  mongo_password:
    file: ./../../.mongo/mongo_password
  mongo_username:
    file: ./../../.mongo/mongo_username
  mongo_tls_keyfile_password:
    file: ./../../.mongo/mongo_tls_keyfile_password
