#!/bin/bash

#
# Technoplatz BI
#
# Copyright (C) 2019-2023 Technoplatz IT Solutions GmbH, Mustafa Mat
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses.
#
# If your software can interact with users remotely through a computer
# network, you should also make sure that it provides a way for users to
# get its source.  For example, if your program is a web application, its
# interface could display a "Source" link that leads users to an archive
# of the code.  There are many ways you could offer source, and different
# solutions will be better for different programs; see section 13 for the
# specific requirements.
#
# You should also get your employer (if you work as a programmer) or school,
# if any, to sign a "copyright disclaimer" for the program, if necessary.
# For more information on this, and how to apply and follow the GNU AGPL, see
# https://www.gnu.org/licenses.
#

cat <<EOF

Technoplatz BI
Copyright 2019-$(date +'%Y'), Technoplatz IT Solutions GmbH
https://bi.technoplatz.com

EOF

function helpBI() {
    echo "Available commands:"
    echo "./bi.sh install"
    echo "./bi.sh start"
    echo "./bi.sh restart"
    echo "./bi.sh stop"
    echo "./bi.sh update"
    echo "./bi.sh prune [--all]"
    echo "./bi.sh logs api|pwa|init|replicaset [last n rows]"
    echo "./bi.sh help"
}

function installBI() {
    if [ -d $DIR ]; then
        while true; do
            read -p "$(echo -e "Oops! An existing ${COLOR}$DIR${NOCOLOR} folder found. Do you want to remove it? (Y/n) ")" yn
            case $yn in
            [Y]*)
                if [[ -f $DIR/$DOTENV ]]; then
                    BKFILE=$DOTENV.bak.$(date '+%Y%m%d%H%M%S')
                    cp $DIR/$DOTENV $DIR/$BKFILE
                    echo -e "✔ Existing parameter file ${COLOR}$DIR/$DOTENV${NOCOLOR} has been backed up as ${COLOR}$DIR/$BKFILE${NOCOLOR}."
                fi
                rm -rf $DIR
                break
                ;;
            [Nn]*)
                echo -e "✘ Installation canceled."
                return 0
                ;;
            *)
                echo -e "✘ Please enter ${COLOR}Y${NOCOLOR} or ${COLOR}n${NOCOLOR}."
                ;;
            esac
        done
    fi
    echo -e "✔ Installation started."
    declare -a curlHeaders=("-H" "Accept: application/vnd.github.v3.raw")
    if [ $TOKEN ]; then
        curlHeaders+=("-H" "Authorization: token $TOKEN")
    fi
    curl "${curlHeaders[@]}" -Ls -o $DIR/$DCYML -o $DIR/$DOTENV $RAWREPO/{$DCYML,$DOTENV}
    CONTD=$(cat $DIR/$DCYML | head -c 3)
    if [[ "$CONTD" == *"40"* || ! -z $DIR/$DCYML || -z $DIR/$DOTENV ]]; then
        echo -e "✘ Sorry! Required files not received successfully $CONTD."
        echo -e "You can retry by adding a token ${COLOR}./bi.sh install [token]${NOCOLOR} as the way to get connected privately."
        return 0
    else
        echo "✔ Required files received successfully."
    fi
    echo "✔ The first step completed successfully."
    echo ">>> NEXT STEPS:"
    echo -e "${COLOR}>>> Please note that your project folder is $DIR${NOCOLOR}"
    echo -e ">>> 1. Open ${COLOR}$DIR$/.env${NOCOLOR} file with any text editor."
    echo ">>> 2. Apply the necessary changes and save it."
    echo -e ">>> 3. Run ${COLOR}./bi.sh start${NOCOLOR} to make containers up and keep them running."
    echo "Here you go :)"
    return 1
}

function updateBI() {
    echo "Updating platform..."
    if [ ! -d $DIR ]; then
        echo -e "✘ Sorry! ${COLOR}$DIR${NOCOLOR} folder not found in the directory you are."
        return 0
    fi
    declare -a curlHeaders=("-H" "Accept: application/vnd.github.v3.raw")
    if [ $TOKEN ]; then
        curlHeaders+=("-H" "Authorization: token $TOKEN")
    fi
    curl "${curlHeaders[@]}" -Lso $DIR/$DCYML.bak $RAWREPO/{$DCYML}
    CONTD=$(cat $DIR/$DCYML.bak | head -c 3)
    if [[ -z $DIR/$DCYML.bak || "$CONTD" == *"40"* ]]; then
        echo -e "✘ Sorry! Configuration file not received from repository ($CONTD)."
        echo -e "You may try to add your token ${COLOR}./bi.sh update [token]${NOCOLOR} as the way to get connected privately."
        rm $DIR/$DCYML.bak
        return 0
    else
        mv -f $DIR/$DCYML.bak $DIR/$DCYML
        echo "✔ Configuration file received successfully."
    fi
    curl "${curlHeaders[@]}" -Lso $ROOTPATH/bi-sh.bak $RAWREPO/bi-sh
    CONTD=$(cat $ROOTPATH/bi-sh.bak | head -c 3)
    if [[ -z $ROOTPATH/bi-sh.bak || "$CONTD" == *"40"* ]]; then
        echo -e "✘ Sorry! Service script not received from repository ($CONTD)."
        echo -e "You may try to add your token ${COLOR}./bi.sh update [token]${NOCOLOR} as the way to get connected privately."
        rm $ROOTPATH/bi-sh.bak
        return 0
    else
        mv -f $ROOTPATH/bi-sh.bak $ROOTPATH/bi.sh
        chmod +x $ROOTPATH/bi.sh
        echo "✔ Service script received successfully."
    fi
    docker compose -f $DIR/$DCYML pull
    if [ $? -eq 0 ]; then
        startBI
        echo -e "✔ The latest version received successfully."
    else
        echo -e "✘ Sorry! Process was terminated ($?)."
        return 0
    fi
    return 1
}

function pruneBI() {
    echo -e "Cleaning..."
    docker system prune --force $1
    if [ $? -eq 0 ]; then
        echo "✔ Dangling and unused resources successfully removed."
    else
        echo -e "✘ Sorry! Process was terminated ($?)."
        return 0
    fi
    return 1
}

function startBI() {
    echo "Starting containers..."
    if [ ! -d $DIR ]; then
        echo -e "✘ Sorry! ${COLOR}$DIR${NOCOLOR} folder not found in the directory you are."
        echo -e "You need to start installation with ${COLOR}./bi.sh install${NOCOLOR} command."
        return 0
    fi
    docker compose -f $DIR/$DCYML up --detach --remove-orphans --no-build
    if [ $? -eq 0 ]; then
        echo -e "✔ Platform is up and running."
    else
        echo -e "✘ Sorry! Process was terminated ($?)."
        return 0
    fi
    return 1
}

function stopBI() {
    echo "Stopping containers..."
    if [[ ! -z $(docker container ls -qa) ]]; then
        docker container stop $(docker container ls -qa)
        docker container rm $(docker container ls -qa)
        if [ $? -eq 0 ]; then
            echo "✔ Running containers stopped and removed successfully."
        else
            echo "✘ Sorry! Process was terminated ($?)."
            return 0
        fi
    else
        echo -e "✘ No active container found!"
    fi
    return 1
}

function logsBI() {
    if [ ! $1 ]; then
        echo "✘ Sorry! You need to provide a docker service ID."
        echo "Command should be given like ./bi.sh logs api|pwa|init|replicaset"
        return 0
    fi
    TAIL=$LOGTAIL
    if [[ ! -z $2 ]]; then
        TAIL=$2
    fi
    echo "Getting the last $TAIL rows from $1 log..."
    docker logs --tail $TAIL $1
    return 1
}

function buildBI() {
    if [ ! $1 ]; then
        echo "✘ Sorry! You need to provide a image ID."
        return 0
    fi
    if [ ! $2 ]; then
        echo "✘ Sorry! You need to provide a folder."
        return 0
    fi
    echo "Building $1 from $2..."
    docker build --tag $1 $2
    if [ $? -ne 0 ]; then
        echo "✘ Sorry! An error occured."
        return 0
    fi
    startBI
    return 1
}

# ENV VARIABLES
COLOR='\033[0;31m'
NOCOLOR='\033[0m'
DCYML="docker-compose.yml"
DOTENV=".env"
TOKEN=""
LOGTAIL=20
RAWREPO="https://raw.githubusercontent.com/Technoplatz/bi/main"

if [[ ! -z $2 ]]; then
    if [[ "$2" == *"-dev"* ]]; then
        if [[ ! -z $3 ]]; then
            if [[ $1 == "update" || $1 == "install" ]]; then
                TOKEN="$3"
            fi
        fi
    else
        if [[ $1 == "update" || $1 == "install" ]]; then
            TOKEN="$2"
        fi
    fi
fi

ROOTPATH="."
DIR=$ROOTPATH/__bi

case $1 in
"install")
    installBI
    ;;
"start")
    startBI
    ;;
"restart")
    stopBI
    startBI
    ;;
"stop")
    stopBI
    ;;
"prune")
    pruneBI "$2"
    ;;
"update")
    updateBI
    ;;
"logs")
    logsBI "$2" "$3"
    ;;
"build")
    buildBI "$2" "$3"
    ;;
"help")
    helpBI
    ;;
*)
    echo "✘ Sorry. $1 is not an available command."
    helpBI
    ;;
esac

echo
