#
# Technoplatz BI
#
# Copyright (C) 2019-2024 Technoplatz IT Solutions GmbH, Mustafa Mat
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses.
#
# If your software can interact with users remotely through a computer
# network, you should also make sure that it provides a way for users to
# get its source.  For example, if your program is a web application, its
# interface could display a "Source" link that leads users to an archive
# of the code.  There are many ways you could offer source, and different
# solutions will be better for different programs; see section 13 for the
# specific requirements.
#
# You should also get your employer (if you work as a programmer) or school,
# if any, to sign a "copyright disclaimer" for the program, if necessary.
# For more information on this, and how to apply and follow the GNU AGPL, see
# https://www.gnu.org/licenses.
#

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=network0
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.service=api@internal
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
      - "${TRAEFIK_CONTAINER_PORT}:${TRAEFIK_CONTAINER_PORT}"
    networks:
      - network0

  init:
    build:
      context: ./init
      dockerfile: Dockerfile
    image: technoplatz/bi-init${REF}:${VERSION}
    container_name: init
    hostname: init
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}
    volumes:
      - bi-cert-volume:/cert
      - bi-mongo0-volume:/data/db
      - bi-mongo0-volume:/data/configdb
      - bi-storage-volume:${API_TEMPFILE_PATH}
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - MONGO_HOST0=${MONGO_HOST0}
      - MONGO_HOST1=${MONGO_HOST1}
      - MONGO_HOST2=${MONGO_HOST2}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - COMPANY_NAME=${COMPANY_NAME}
      - DEPARTMENT_NAME=${DEPARTMENT_NAME}
      - COUNTRY_CODE=${COUNTRY_CODE}
      - STATE_NAME=${STATE_NAME}
      - CITY_NAME=${CITY_NAME}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE}
      - MONGO_SELF_SIGNED_CERTS=${MONGO_SELF_SIGNED_CERTS}
      - MONGO_CERTS_REPLACE=${MONGO_CERTS_REPLACE}
      - MONGO_TLS_CA_KEYFILE=${MONGO_TLS_CA_KEYFILE}
      - MONGO_TLS_CERT_KEYFILE=${MONGO_TLS_CERT_KEYFILE}
      - MONGO_TLS_CERT_KEYFILE_PASSWORD=${MONGO_TLS_CERT_KEYFILE_PASSWORD}
      - API_TEMPFILE_PATH=${API_TEMPFILE_PATH}
    networks:
      - network0

  mongo0:
    image: mongo:${MONGO_VERSION}
    container_name: mongo0
    hostname: ${MONGO_HOST0}
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh "mongodb://${MONGO_HOST0}:$MONGO_PORT0/test" --quiet --tls --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword ${MONGO_TLS_CERT_KEYFILE_PASSWORD} --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates
    depends_on:
      init:
        condition: service_completed_successfully
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}
    ports:
      - "${MONGO_PORT0}:${MONGO_PORT0}"
    volumes:
      - bi-cert-volume:/cert:ro
      - bi-mongo0-volume:/data/db
      - bi-mongo0-volume:/data/configdb
      - bi-log-volume:/log/mongodb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: "/usr/bin/mongod --bind_ip_all --dbpath /data/db --logpath /log/mongodb/${MONGO_HOST0}.log --logappend --quiet --replSet ${MONGO_RS} --port ${MONGO_PORT0} --tlsMode requireTLS --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword ${MONGO_TLS_CERT_KEYFILE_PASSWORD} --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates --timeZoneInfo /usr/share/zoneinfo"
    links:
      - init
      - mongo1
      - mongo2
    networks:
      - network0

  mongo1:
    image: mongo:${MONGO_VERSION}
    container_name: mongo1
    hostname: ${MONGO_HOST1}
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh "mongodb://${MONGO_HOST1}:$MONGO_PORT0/test" --quiet --tls --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword ${MONGO_TLS_CERT_KEYFILE_PASSWORD} --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates
    depends_on:
      init:
        condition: service_completed_successfully
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}
    ports:
      - "${MONGO_PORT1}:${MONGO_PORT0}"
    volumes:
      - bi-cert-volume:/cert:ro
      - bi-mongo1-volume:/data/db
      - bi-mongo1-volume:/data/configdb
      - bi-log-volume:/log/mongodb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: "/usr/bin/mongod --bind_ip_all --dbpath /data/db --logpath /log/mongodb/${MONGO_HOST1}.log --logappend --quiet --replSet ${MONGO_RS} --port ${MONGO_PORT0} --tlsMode requireTLS --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword ${MONGO_TLS_CERT_KEYFILE_PASSWORD} --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates --timeZoneInfo /usr/share/zoneinfo"
    links:
      - init
    networks:
      - network0

  mongo2:
    image: mongo:${MONGO_VERSION}
    container_name: mongo2
    hostname: ${MONGO_HOST2}
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh "mongodb://${MONGO_HOST2}:$MONGO_PORT0/test" --quiet --tls --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword ${MONGO_TLS_CERT_KEYFILE_PASSWORD} --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates
    depends_on:
      init:
        condition: service_completed_successfully
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}
    ports:
      - "${MONGO_PORT2}:${MONGO_PORT0}"
    volumes:
      - bi-cert-volume:/cert:ro
      - bi-mongo2-volume:/data/db
      - bi-mongo2-volume:/data/configdb
      - bi-log-volume:/log/mongodb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    command: "/usr/bin/mongod --bind_ip_all --dbpath /data/db --logpath /log/mongodb/${MONGO_HOST2}.log --logappend --quiet --replSet ${MONGO_RS} --port ${MONGO_PORT0} --tlsMode requireTLS --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword ${MONGO_TLS_CERT_KEYFILE_PASSWORD} --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates --timeZoneInfo /usr/share/zoneinfo"
    links:
      - init
    networks:
      - network0

  replicaset:
    build:
      context: ./replicaset
      dockerfile: Dockerfile
    image: technoplatz/bi-replicaset${REF}:${VERSION}
    container_name: replicaset
    hostname: replicaset
    depends_on:
      mongo0:
        condition: service_healthy
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}
    volumes:
      - bi-cert-volume:/cert
      - bi-mongo0-volume:/data/db
      - bi-mongo0-volume:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_NAME=${ADMIN_NAME}
      - COMPANY_NAME=${COMPANY_NAME}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE}
      - MONGO_DB=${MONGO_DB}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST0=${MONGO_HOST0}
      - MONGO_HOST1=${MONGO_HOST1}
      - MONGO_HOST2=${MONGO_HOST2}
      - MONGO_PORT0=${MONGO_PORT0}
      - MONGO_PORT1=${MONGO_PORT1}
      - MONGO_PORT2=${MONGO_PORT2}
      - MONGO_RS=${MONGO_RS}
      - MONGO_TLS=${MONGO_TLS}
      - MONGO_TLS_CA_KEYFILE=${MONGO_TLS_CA_KEYFILE}
      - MONGO_TLS_CERT_KEYFILE=${MONGO_TLS_CERT_KEYFILE}
      - MONGO_TLS_CERT_KEYFILE_PASSWORD=${MONGO_TLS_CERT_KEYFILE_PASSWORD}
      - MONGO_TLS_ALLOW_INVALID_CERTIFICATES=${MONGO_TLS_ALLOW_INVALID_CERTIFICATES}
      - MONGO_RETRY_WRITES=${MONGO_RETRY_WRITES}
    links:
      - mongo0
      - mongo1
      - mongo2
    networks:
      - network0

  stream:
    build:
      context: ./backend/stream
      dockerfile: Dockerfile
    image: technoplatz/bi-stream${REF}:${VERSION}
    container_name: stream
    depends_on:
      replicaset:
        condition: service_completed_successfully
    hostname: stream
    restart: always
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}
    volumes:
      - bi-cert-volume:/cert
      - bi-storage-volume:${API_TEMPFILE_PATH}
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${STREAM_CONTAINER_PORT}:${STREAM_CONTAINER_PORT}"
    environment:
      - TZ=${TZ}
      - MONGO_DB=${MONGO_DB}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST0=${MONGO_HOST0}
      - MONGO_HOST1=${MONGO_HOST1}
      - MONGO_HOST2=${MONGO_HOST2}
      - MONGO_PORT0=${MONGO_PORT0}
      - MONGO_PORT1=${MONGO_PORT1}
      - MONGO_PORT2=${MONGO_PORT2}
      - MONGO_RS=${MONGO_RS}
      - MONGO_TLS=${MONGO_TLS}
      - MONGO_TLS_CA_KEYFILE=${MONGO_TLS_CA_KEYFILE}
      - MONGO_TLS_CERT_KEYFILE=${MONGO_TLS_CERT_KEYFILE}
      - MONGO_TLS_ALLOW_INVALID_CERTIFICATES=${MONGO_TLS_ALLOW_INVALID_CERTIFICATES}
      - MONGO_RETRY_WRITES=${MONGO_RETRY_WRITES}
      - SMTP_ENDPOINT=${SMTP_ENDPOINT}
      - SMTP_USERID=${SMTP_USERID}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_TLS_PORT=${SMTP_TLS_PORT}
      - FROM_EMAIL=${FROM_EMAIL}
      - COMPANY_NAME=${COMPANY_NAME}
      - NOTIFICATION_PUSH_URL=${NOTIFICATION_PUSH_URL}
      - API_TEMPFILE_PATH=${API_TEMPFILE_PATH}
      - HTML_TABLE_MAX_ROWS=${HTML_TABLE_MAX_ROWS}
      - HTML_TABLE_MAX_COLS=${HTML_TABLE_MAX_COLS}
    links:
      - replicaset
    networks:
      - network0

  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    image: technoplatz/bi-api${REF}:${VERSION}
    container_name: api
    depends_on:
      stream:
        condition: service_started
    hostname: api
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=network0
      - traefik.http.routers.api.rule=Host(`${DOMAIN}`) && PathPrefix(`/api`)
      - traefik.http.services.api.loadbalancer.server.port=${HTTP_PORT}
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}
    volumes:
      - bi-storage-volume:${API_TEMPFILE_PATH}
      - bi-storage-volume:${API_MONGODUMP_PATH}
      - bi-storage-volume:/cron
      - bi-cert-volume:/cert
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${API_CONTAINER_PORT}:${HTTP_PORT}"
    environment:
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
      - COMPANY_NAME=${COMPANY_NAME}
      - FROM_EMAIL=${FROM_EMAIL}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - DEFAULT_LOCALE=${DEFAULT_LOCALE}
      - MONGO_DB=${MONGO_DB}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST0=${MONGO_HOST0}
      - MONGO_HOST1=${MONGO_HOST1}
      - MONGO_HOST2=${MONGO_HOST2}
      - MONGO_PORT0=${MONGO_PORT0}
      - MONGO_PORT1=${MONGO_PORT1}
      - MONGO_PORT2=${MONGO_PORT2}
      - MONGO_RS=${MONGO_RS}
      - MONGO_DUMP_HOURS=${MONGO_DUMP_HOURS}
      - MONGO_TLS=${MONGO_TLS}
      - MONGO_TLS_CA_KEYFILE=${MONGO_TLS_CA_KEYFILE}
      - MONGO_TLS_CERT_KEYFILE=${MONGO_TLS_CERT_KEYFILE}
      - MONGO_TLS_ALLOW_INVALID_CERTIFICATES=${MONGO_TLS_ALLOW_INVALID_CERTIFICATES}
      - MONGO_RETRY_WRITES=${MONGO_RETRY_WRITES}
      - MONGO_TIMEOUT_MS=${MONGO_TIMEOUT_MS}
      - SMTP_ENDPOINT=${SMTP_ENDPOINT}
      - SMTP_USERID=${SMTP_USERID}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_TLS_PORT=${SMTP_TLS_PORT}
      - EMAIL_SUBJECT_PREFIX=${EMAIL_SUBJECT_PREFIX}
      - EMAIL_DISCLAIMER_HTML=${EMAIL_DISCLAIMER_HTML}
      - API_SCHEDULE_INTERVAL_MIN=${API_SCHEDULE_INTERVAL_MIN}
      - API_FW_TEMP_DURATION_MIN=${API_FW_TEMP_DURATION_MIN}
      - API_SESSION_EXP_MINUTES=${API_SESSION_EXP_MINUTES}
      - API_OUTPUT_ROWS_LIMIT=${API_OUTPUT_ROWS_LIMIT}
      - API_JOB_UPDATE_LIMIT=${API_JOB_UPDATE_LIMIT}
      - API_UPLOAD_LIMIT_BYTES=${API_UPLOAD_LIMIT_BYTES}
      - API_MAX_CONTENT_LENGTH_MB=${API_MAX_CONTENT_LENGTH_MB}
      - API_DEFAULT_AGGREGATION_LIMIT=${API_DEFAULT_AGGREGATION_LIMIT}
      - API_DEFAULT_VISUAL_LIMIT=${API_DEFAULT_VISUAL_LIMIT}
      - API_QUERY_PAGE_SIZE=${API_QUERY_PAGE_SIZE}
      - API_TEMPFILE_PATH=${API_TEMPFILE_PATH}
      - API_MONGODUMP_PATH=${API_MONGODUMP_PATH}
      - API_S3_ACTIVE=${API_S3_ACTIVE}
      - API_S3_REGION=${API_S3_REGION}
      - API_S3_BUCKET_NAME=${API_S3_BUCKET_NAME}
      - API_S3_KEY_ID=${API_S3_KEY_ID}
      - API_S3_KEY=${API_S3_KEY}
      - API_PERMISSIVE_TAGS=${API_PERMISSIVE_TAGS}
      - API_ADMIN_TAGS=${API_ADMIN_TAGS}
      - API_ADMIN_IPS=${API_ADMIN_IPS}
      - API_DELETE_ALLOWED=${API_DELETE_ALLOWED}
      - API_CORS_ORIGINS=${API_CORS_ORIGINS}
      - NOTIFICATION_PUSH_URL=${NOTIFICATION_PUSH_URL}
      - RESTAPI_ENABLED=${RESTAPI_ENABLED}
      - HTML_TABLE_MAX_ROWS=${HTML_TABLE_MAX_ROWS}
      - HTML_TABLE_MAX_COLS=${HTML_TABLE_MAX_COLS}
    links:
      - replicaset
    networks:
      - network0

  pwa:
    build:
      context: ./pwa
      dockerfile: Dockerfile
    image: technoplatz/bi-pwa${REF}:${VERSION}
    container_name: pwa
    depends_on:
      api:
        condition: service_started
    hostname: pwa
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=network0
      - traefik.http.routers.pwa.rule=Host(`${DOMAIN}`) && !PathPrefix(`/api`)
      - traefik.http.routers.pwa.priority=0
      - traefik.http.services.pwa.loadbalancer.server.port=${HTTP_PORT}
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${PWA_CONTAINER_PORT}:${HTTP_PORT}"
    environment:
      - TZ=${TZ}
      - API_URL=${API_URL}
      - COMPANY_NAME=${COMPANY_NAME}
    links:
      - api
    networks:
      - network0

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    restart: always
    labels:
      - traefik.enable=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=${NOTIFICATION_IDENTIFIER}
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${NOTIFICATION_PUSH_URL}
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_INTERVAL_SECONDS}
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
      - WATCHTOWER_ROLLING_RESTART=${WATCHTOWER_ROLLING_RESTART}
    links:
      - traefik
    networks:
      - network0

volumes:
  bi-mongo0-volume:
    name: bi-mongo0-volume
    driver: local
  bi-mongo1-volume:
    name: bi-mongo1-volume
    driver: local
  bi-mongo2-volume:
    name: bi-mongo2-volume
    driver: local
  bi-storage-volume:
    name: bi-storage-volume
    driver: local
  bi-cert-volume:
    name: bi-cert-volume
    driver: local
  bi-log-volume:
    name: bi-log-volume
    driver: local

networks:
  network0:
    name: network0
    ipam:
      driver: default
