#
# Technoplatz BI
#
# Copyright (C) 2019-2023 Technoplatz IT Solutions GmbH, Mustafa Mat
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see https://www.gnu.org/licenses.
#
# If your software can interact with users remotely through a computer
# network, you should also make sure that it provides a way for users to
# get its source.  For example, if your program is a web application, its
# interface could display a "Source" link that leads users to an archive
# of the code.  There are many ways you could offer source, and different
# solutions will be better for different programs; see section 13 for the
# specific requirements.
#
# You should also get your employer (if you work as a programmer) or school,
# if any, to sign a "copyright disclaimer" for the program, if necessary.
# For more information on this, and how to apply and follow the GNU AGPL, see
# https://www.gnu.org/licenses.
#

version: "3.9"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=network0
      - traefik.http.routers.bi-traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.bi-traefik.service=api@internal
      - com.centurylinklabs.watchtower.enable=true
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${HTTPS_PORT}:${HTTPS_PORT}"
      - "${TRAEFIK_PORT}:${TRAEFIK_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
    networks:
      network0:
        ipv4_address: ${SUBNET_TRAEFIK_IPV4}

  init:
    build:
      context: ./init
      dockerfile: Dockerfile
    image: ghcr.io/technoplatz/bi-init:latest
    container_name: init
    hostname: init
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - bi-cert-volume:/cert
      - bi-mongo0-volume:/data/db
      - bi-mongo0-volume:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGO_HOST0=${MONGO_HOST0}
      - MONGO_HOST1=${MONGO_HOST1}
      - MONGO_HOST2=${MONGO_HOST2}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - COMPANY_NAME=${COMPANY_NAME}
      - DEPARTMENT_NAME=${DEPARTMENT_NAME}
      - COUNTRY_CODE=${COUNTRY_CODE}
      - STATE_NAME=${STATE_NAME}
      - CITY_NAME=${CITY_NAME}
      - MONGO_SELF_SIGNED_CERTS=${MONGO_SELF_SIGNED_CERTS}
      - MONGO_CERTS_REPLACE=${MONGO_CERTS_REPLACE}
      - MONGO_TLS_CA_KEYFILE=${MONGO_TLS_CA_KEYFILE}
      - MONGO_TLS_CERT_KEYFILE=${MONGO_TLS_CERT_KEYFILE}
    networks:
      network0:
        ipv4_address: ${SUBNET_INIT_IPV4}
    secrets:
      - mongo_tls_keyfile_password

  mongo0:
    image: mongo:latest
    container_name: mongo0
    hostname: ${MONGO_HOST0}
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh "mongodb://${SUBNET_MONGO0_IPV4}:$MONGO_PORT0/test" --quiet --tls --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword ${MONGO_TLS_CERT_KEYFILE_PASSWORD} --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates
    depends_on:
      init:
        condition: service_completed_successfully
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - "${MONGO_PORT0}:${MONGO_PORT0}"
    volumes:
      - bi-cert-volume:/cert:ro
      - bi-mongo0-volume:/data/db
      - bi-mongo0-volume:/data/configdb
      - bi-log-volume:/log/mongodb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_initdb_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_initdb_root_password
      - MONGO_USERNAME_FILE=/run/secrets/mongo_username
      - MONGO_PASSWORD_FILE=/run/secrets/mongo_password
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    command: "/usr/bin/mongod --bind_ip ${SUBNET_MONGO0_IPV4} --dbpath /data/db --logpath /log/mongodb/${MONGO_HOST0}.log --logappend --quiet --replSet ${MONGO_RS} --port ${MONGO_PORT0} --tlsMode requireTLS --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword /run/secrets/mongo_tls_keyfile_password --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates --timeZoneInfo /usr/share/zoneinfo"
    links:
      - init
      - mongo1
      - mongo2
    networks:
      network0:
        ipv4_address: ${SUBNET_MONGO0_IPV4}
    secrets:
      - mongo_initdb_root_username
      - mongo_initdb_root_password
      - mongo_username
      - mongo_password
      - mongo_tls_keyfile_password

  mongo1:
    image: mongo:latest
    container_name: mongo1
    hostname: ${MONGO_HOST1}
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh "mongodb://${SUBNET_MONGO1_IPV4}:$MONGO_PORT0/test" --quiet --tls --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword ${MONGO_TLS_CERT_KEYFILE_PASSWORD} --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates
    depends_on:
      init:
        condition: service_completed_successfully
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - "${MONGO_PORT1}:${MONGO_PORT0}"
    volumes:
      - bi-cert-volume:/cert:ro
      - bi-mongo1-volume:/data/db
      - bi-mongo1-volume:/data/configdb
      - bi-log-volume:/log/mongodb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_initdb_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_initdb_root_password
      - MONGO_USERNAME_FILE=/run/secrets/mongo_username
      - MONGO_PASSWORD_FILE=/run/secrets/mongo_password
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    command: "/usr/bin/mongod --bind_ip ${SUBNET_MONGO1_IPV4} --dbpath /data/db --logpath /log/mongodb/${MONGO_HOST1}.log --logappend --quiet --replSet ${MONGO_RS} --port ${MONGO_PORT0} --tlsMode requireTLS --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword /run/secrets/mongo_tls_keyfile_password --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates --timeZoneInfo /usr/share/zoneinfo"
    links:
      - init
    networks:
      network0:
        ipv4_address: ${SUBNET_MONGO1_IPV4}
    secrets:
      - mongo_initdb_root_username
      - mongo_initdb_root_password
      - mongo_username
      - mongo_password
      - mongo_tls_keyfile_password

  mongo2:
    image: mongo:latest
    container_name: mongo2
    hostname: ${MONGO_HOST2}
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh "mongodb://${SUBNET_MONGO2_IPV4}:$MONGO_PORT0/test" --quiet --tls --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword ${MONGO_TLS_CERT_KEYFILE_PASSWORD} --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates
    depends_on:
      init:
        condition: service_completed_successfully
    labels:
      - com.centurylinklabs.watchtower.enable=true
    ports:
      - "${MONGO_PORT2}:${MONGO_PORT0}"
    volumes:
      - bi-cert-volume:/cert:ro
      - bi-mongo2-volume:/data/db
      - bi-mongo2-volume:/data/configdb
      - bi-log-volume:/log/mongodb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_initdb_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_initdb_root_password
      - MONGO_USERNAME_FILE=/run/secrets/mongo_username
      - MONGO_PASSWORD_FILE=/run/secrets/mongo_password
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    command: "/usr/bin/mongod --bind_ip ${SUBNET_MONGO2_IPV4} --dbpath /data/db --logpath /log/mongodb/${MONGO_HOST2}.log --logappend --quiet --replSet ${MONGO_RS} --port ${MONGO_PORT0} --tlsMode requireTLS --tlsCertificateKeyFile ${MONGO_TLS_CERT_KEYFILE} --tlsCertificateKeyFilePassword /run/secrets/mongo_tls_keyfile_password --tlsCAFile ${MONGO_TLS_CA_KEYFILE} --tlsAllowInvalidCertificates --timeZoneInfo /usr/share/zoneinfo"
    links:
      - init
    networks:
      network0:
        ipv4_address: ${SUBNET_MONGO2_IPV4}
    secrets:
      - mongo_initdb_root_username
      - mongo_initdb_root_password
      - mongo_username
      - mongo_password
      - mongo_tls_keyfile_password

  replicaset:
    build:
      context: ./replicaset
      dockerfile: Dockerfile
    image: ghcr.io/technoplatz/bi-replicaset:latest
    container_name: replicaset
    hostname: replicaset
    depends_on:
      mongo0:
        condition: service_healthy
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - bi-cert-volume:/cert
      - bi-mongo0-volume:/data/db
      - bi-mongo0-volume:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_NAME=${ADMIN_NAME}
      - COMPANY_NAME=${COMPANY_NAME}
      - MONGO_DB=${MONGO_DB}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - MONGO_HOST0=${MONGO_HOST0}
      - MONGO_HOST1=${MONGO_HOST1}
      - MONGO_HOST2=${MONGO_HOST2}
      - MONGO_PORT0=${MONGO_PORT0}
      - MONGO_PORT1=${MONGO_PORT1}
      - MONGO_PORT2=${MONGO_PORT2}
      - MONGO_RS=${MONGO_RS}
      - MONGO_TLS=${MONGO_TLS}
      - MONGO_TLS_CA_KEYFILE=${MONGO_TLS_CA_KEYFILE}
      - MONGO_TLS_CERT_KEYFILE=${MONGO_TLS_CERT_KEYFILE}
      - MONGO_TLS_ALLOW_INVALID_CERTIFICATES=${MONGO_TLS_ALLOW_INVALID_CERTIFICATES}
      - MONGO_RETRY_WRITES=${MONGO_RETRY_WRITES}
    links:
      - mongo0
      - mongo1
      - mongo2
    networks:
      network0:
        ipv4_address: ${SUBNET_REPLICASET_IPV4}
    secrets:
      - mongo_username
      - mongo_password
      - mongo_tls_keyfile_password

  stream:
    build:
      context: ./backend/stream
      dockerfile: Dockerfile
    image: ghcr.io/technoplatz/bi-stream:latest
    container_name: stream
    depends_on:
      replicaset:
        condition: service_completed_successfully
    hostname: stream
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - bi-cert-volume:/cert
      - bi-storage-volume:/docs
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${STREAM_PORT}:80"
    environment:
      - MONGO_DB=${MONGO_DB}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - MONGO_HOST0=${MONGO_HOST0}
      - MONGO_HOST1=${MONGO_HOST1}
      - MONGO_HOST2=${MONGO_HOST2}
      - MONGO_PORT0=${MONGO_PORT0}
      - MONGO_PORT1=${MONGO_PORT1}
      - MONGO_PORT2=${MONGO_PORT2}
      - MONGO_RS=${MONGO_RS}
      - MONGO_TLS=${MONGO_TLS}
      - MONGO_TLS_CA_KEYFILE=${MONGO_TLS_CA_KEYFILE}
      - MONGO_TLS_CERT_KEYFILE=${MONGO_TLS_CERT_KEYFILE}
      - MONGO_TLS_ALLOW_INVALID_CERTIFICATES=${MONGO_TLS_ALLOW_INVALID_CERTIFICATES}
      - MONGO_RETRY_WRITES=${MONGO_RETRY_WRITES}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERID=${SMTP_USERID}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FROM_EMAIL=${FROM_EMAIL}
      - COMPANY_NAME=${COMPANY_NAME}
      - NOTIFICATION_SLACK_HOOK_URL=${NOTIFICATION_SLACK_HOOK_URL}
    links:
      - replicaset
    extra_hosts:
      - mongo0:${SUBNET_MONGO0_IPV4}
      - mongo1:${SUBNET_MONGO1_IPV4}
      - mongo2:${SUBNET_MONGO2_IPV4}
    networks:
      network0:
        ipv4_address: ${SUBNET_STREAM_IPV4}
    secrets:
      - mongo_username
      - mongo_password
      - mongo_tls_keyfile_password

  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    image: ghcr.io/technoplatz/bi-api:latest
    container_name: api
    depends_on:
      stream:
        condition: service_started
    hostname: api
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=network0
      - traefik.http.routers.api.rule=Host(`api.${DOMAIN}`)
      - traefik.http.services.api.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - bi-storage-volume:/cron
      - bi-storage-volume:/docs
      - bi-storage-volume:/dump
      - bi-storage-volume:/vault
      - bi-cert-volume:/cert
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${API_PORT}:80"
    environment:
      - DOMAIN=${DOMAIN}
      - COMPANY_NAME=${COMPANY_NAME}
      - FROM_EMAIL=${FROM_EMAIL}
      - MONGO_DB=${MONGO_DB}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - MONGO_HOST0=${MONGO_HOST0}
      - MONGO_HOST1=${MONGO_HOST1}
      - MONGO_HOST2=${MONGO_HOST2}
      - MONGO_PORT0=${MONGO_PORT0}
      - MONGO_PORT1=${MONGO_PORT1}
      - MONGO_PORT2=${MONGO_PORT2}
      - MONGO_RS=${MONGO_RS}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERID=${SMTP_USERID}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_DISCLAIMER_HTML=${EMAIL_DISCLAIMER_HTML}
      - API_SCHEDULE_INTERVAL_MIN=${API_SCHEDULE_INTERVAL_MIN}
      - API_DUMP_HOURS=${API_DUMP_HOURS}
      - API_SESSION_EXP_MINUTES=${API_SESSION_EXP_MINUTES}
      - API_OUTPUT_ROWS_LIMIT=${API_OUTPUT_ROWS_LIMIT}
      - API_UPLOAD_LIMIT_BYTES=${API_UPLOAD_LIMIT_BYTES}
      - API_MAX_CONTENT_LENGTH=${API_MAX_CONTENT_LENGTH}
      - API_DEFAULT_AGGREGATION_LIMIT=${API_DEFAULT_AGGREGATION_LIMIT}
      - API_QUERY_PAGE_SIZE=${API_QUERY_PAGE_SIZE}
      - API_WORKFILE_PATH=${API_WORKFILE_PATH}
      - API_DUMPFILE_PATH=${API_DUMPFILE_PATH}
      - NOTIFICATION_SLACK_HOOK_URL=${NOTIFICATION_SLACK_HOOK_URL}
      - MONGO_TLS=${MONGO_TLS}
      - MONGO_TLS_CA_KEYFILE=${MONGO_TLS_CA_KEYFILE}
      - MONGO_TLS_CERT_KEYFILE=${MONGO_TLS_CERT_KEYFILE}
      - MONGO_TLS_ALLOW_INVALID_CERTIFICATES=${MONGO_TLS_ALLOW_INVALID_CERTIFICATES}
      - MONGO_RETRY_WRITES=${MONGO_RETRY_WRITES}
    links:
      - replicaset
    extra_hosts:
      - mongo0:${SUBNET_MONGO0_IPV4}
      - mongo1:${SUBNET_MONGO1_IPV4}
      - mongo2:${SUBNET_MONGO2_IPV4}
    networks:
      network0:
        ipv4_address: ${SUBNET_API_IPV4}
    secrets:
      - mongo_username
      - mongo_password
      - mongo_tls_keyfile_password

  pwa:
    build:
      context: ./pwa
      dockerfile: Dockerfile
    image: ghcr.io/technoplatz/bi-pwa:latest
    container_name: pwa
    depends_on:
      api:
        condition: service_started
    hostname: pwa
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=network0
      - traefik.http.routers.pwa.rule=Host(`${DOMAIN}`)
      - traefik.http.services.pwa.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${PWA_PORT}:80"
    links:
      - api
    networks:
      network0:
        ipv4_address: ${SUBNET_PWA_IPV4}

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: --interval ${WATCHTOWER_UPDATE_INTERVAL_MIN}
    environment:
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=${DOMAIN}
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${NOTIFICATION_SLACK_HOOK_URL}
    links:
      - traefik
    networks:
      network0:
        ipv4_address: ${SUBNET_WATCHTOWER_IPV4}

volumes:
  bi-mongo0-volume:
    driver: local
    name: bi-mongo0-volume
  bi-mongo1-volume:
    driver: local
    name: bi-mongo1-volume
  bi-mongo2-volume:
    driver: local
    name: bi-mongo2-volume
  bi-storage-volume:
    driver: local
    name: bi-storage-volume
  bi-cert-volume:
    driver: local
    name: bi-cert-volume
  bi-log-volume:
    driver: local
    name: bi-log-volume

networks:
  network0:
    name: network0
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}

secrets:
  mongo_initdb_root_password:
    file: ./.mongo/mongo_initdb_root_password
  mongo_initdb_root_username:
    file: ./.mongo/mongo_initdb_root_username
  mongo_password:
    file: ./.mongo/mongo_password
  mongo_username:
    file: ./.mongo/mongo_username
  mongo_tls_keyfile_password:
    file: ./.mongo/mongo_tls_keyfile_password
