# Technoplatz BI - Docker Compose
# Mustafa Mat @Technoplatz 2019-2023
# docker-compose --env-file .dev.env --file docker-compose-dev.yml up --build --detach --remove-orphans

version: "3.7"
services:
  traefik:
    container_name: traefik
    image: traefik:latest
    hostname: traefik
    pull_policy: always
    restart: always
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
    labels:
      - traefik.enable=true
      - traefik.docker.network=network0
      - traefik.http.routers.bi-traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.bi-traefik.service=api@internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 443:443
      - 8080:8080
      - 80:80
    environment:
      - TZ=${TZ}
    networks:
      network0:
        ipv4_address: ${SUBNET_TRAEFIK_IPV4}

  init:
    container_name: init
    image: bi-init:latest
    build:
      context: _init/.
      dockerfile: Dockerfile
    hostname: init
    volumes:
      - bi-storage-volume:/init
      - bi-mongo0-volume:/data/db
      - bi-mongo0-volume:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    networks:
      network0:
        ipv4_address: ${SUBNET_INIT_IPV4}

  mongo0:
    container_name: mongo0
    image: mongo:latest
    hostname: ${MONGO_HOST}
    pull_policy: always
    depends_on:
      - init
    restart: always
    expose:
      - ${MONGO_PORT}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - bi-storage-volume:/init:ro
      - bi-mongo0-volume:/data/db
      - bi-mongo0-volume:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./_init/mongod.conf:/etc/mongod.conf
    environment:
      - TZ=${TZ}
    command: "/usr/bin/mongod --config /etc/mongod.conf"
    links:
      - mongo1
      - mongo2
    networks:
      network0:
        ipv4_address: ${SUBNET_MONGO_IPV4}

  mongo1:
    container_name: mongo1
    image: mongo:latest
    hostname: ${MONGO_REPLICA1_HOST}
    pull_policy: always
    depends_on:
      - init
    restart: always
    expose:
      - ${MONGO_PORT}
    ports:
      - "${MONGO_REPLICA1_PORT}:${MONGO_PORT}"
    volumes:
      - bi-storage-volume:/init:ro
      - bi-mongo1-volume:/data/db
      - bi-mongo1-volume:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./_init/mongod.conf:/etc/mongod.conf
    environment:
      - TZ=${TZ}
    command: "/usr/bin/mongod --config /etc/mongod.conf"
    networks:
      network0:
        ipv4_address: ${SUBNET_MONGO_REPLICA1_IPV4}

  mongo2:
    container_name: mongo2
    image: mongo:latest
    hostname: ${MONGO_REPLICA2_HOST}
    pull_policy: always
    depends_on:
      - init
    restart: always
    expose:
      - ${MONGO_PORT}
    ports:
      - "${MONGO_REPLICA2_PORT}:${MONGO_PORT}"
    volumes:
      - bi-storage-volume:/init:ro
      - bi-mongo2-volume:/data/db
      - bi-mongo2-volume:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./_init/mongod.conf:/etc/mongod.conf
    environment:
      - TZ=${TZ}
    command: "/usr/bin/mongod --config /etc/mongod.conf"
    networks:
      network0:
        ipv4_address: ${SUBNET_MONGO_REPLICA2_IPV4}

  replicaset:
    container_name: replicaset
    image: bi-replicaset:latest
    build:
      context: _replicaset/.
      dockerfile: Dockerfile
    hostname: replicaset
    pull_policy: always
    depends_on:
      - mongo0
      - mongo1
      - mongo2
    volumes:
      - bi-storage-volume:/init
      - bi-mongo0-volume:/data/db
      - bi-mongo0-volume:/data/configdb
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_EMAIL=${USER_EMAIL}
      - USER_NAME=${USER_NAME}
      - COMPANY_NAME=${COMPANY_NAME}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_REPLICASET=${MONGO_REPLICASET}
      - MONGO_REPLICA1_HOST=${MONGO_REPLICA1_HOST}
      - MONGO_REPLICA2_HOST=${MONGO_REPLICA2_HOST}
    extra_hosts:
      - mongo0:${SUBNET_MONGO_IPV4}
      - mongo1:${SUBNET_MONGO_REPLICA1_IPV4}
      - mongo2:${SUBNET_MONGO_REPLICA2_IPV4}
    networks:
      network0:
        ipv4_address: ${SUBNET_REPLICASET_IPV4}

  api:
    container_name: api
    image: ghcr.io/technoplatz/bi-api-dev0:latest
    build:
      context: api/.
      dockerfile: Dockerfile
    pull_policy: always
    depends_on:
      - replicaset
    hostname: api
    restart: always
    volumes:
      - bi-storage-volume:/cron
      - bi-storage-volume:/dump
      - bi-storage-volume:/vault
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5001:80
    labels:
      - traefik.enable=true
      - traefik.docker.network=network0
      - traefik.http.routers.api.rule=Host(`api.${DOMAIN}`)
      - traefik.http.services.api.loadbalancer.server.port=80
    environment:
      - TZ=${TZ}
      - DOMAIN=${DOMAIN}
      - COMPANY_NAME=${COMPANY_NAME}
      - FROM_EMAIL=${FROM_EMAIL}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}
      - MONGO_AUTH_DB=${MONGO_AUTH_DB}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_REPLICASET=${MONGO_REPLICASET}
      - MONGO_REPLICA1_HOST=${MONGO_REPLICA1_HOST}
      - MONGO_REPLICA2_HOST=${MONGO_REPLICA2_HOST}
      - PWA_API_KEY=${PWA_API_KEY}
      - API_SCHEDULE_INTERVAL_MIN=${API_SCHEDULE_INTERVAL_MIN}
      - API_DUMP_HOURS=${API_DUMP_HOURS}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SECUR_SALTED_ROUNDS=${SECUR_SALTED_ROUNDS}
      - SECUR_MAX_AGE=${SECUR_MAX_AGE}
      - API_OUTPUT_ROWS_LIMIT=${API_OUTPUT_ROWS_LIMIT}
    links:
      - pwa
    networks:
      network0:
        ipv4_address: ${SUBNET_API_IPV4}

  pwa:
    container_name: pwa
    image: ghcr.io/technoplatz/bi-pwa-dev0:latest
    build:
      context: pwa/.
      dockerfile: Dockerfile
    pull_policy: always
    hostname: pwa
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8100:80
    labels:
      - traefik.enable=true
      - traefik.docker.network=network0
      - traefik.http.routers.pwa.rule=Host(`${DOMAIN}`)
      - traefik.http.services.pwa.loadbalancer.server.port=80
    extra_hosts:
      - api:${SUBNET_API_IPV4}
    networks:
      network0:
        ipv4_address: ${SUBNET_PWA_IPV4}

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    pull_policy: always
    hostname: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    command: --interval 86400 api pwa watchtower traefik
    networks:
      network0:
        ipv4_address: ${SUBNET_WATCHTOWER_IPV4}

volumes:
  bi-mongo0-volume:
    driver: local
    name: bi-mongo0-volume
  bi-mongo1-volume:
    driver: local
    name: bi-mongo1-volume
  bi-mongo2-volume:
    driver: local
    name: bi-mongo2-volume
  bi-storage-volume:
    driver: local
    name: bi-storage-volume

networks:
  network0:
    name: network0
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
