// Writes src/app/icons.ts: every ionicons name mapped to its svg asset, so icons referenced by name
// (in templates and in collection schemas) resolve in the standalone build. Runs as npm prebuild.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const names = readdirSync(join(root, "node_modules/ionicons/dist/ionicons/svg"))
  .filter((f) => f.endsWith(".svg")).map((f) => f.slice(0, -4)).sort();
const out = `// generated by tools/gen-icons.mjs from ionicons ${JSON.parse(readFileSync(join(root, "node_modules/ionicons/package.json"))).version}; do not edit
import { addIcons } from "ionicons";

const NAMES: string[] = ${JSON.stringify(names)};

/** registers every ionicon by name, pointing at the svg copied to the svg/ asset folder */
export function registerIcons() {
  const map: { [name: string]: string } = {};
  for (const name of NAMES) {
    map[name] = \`svg/\${name}.svg\`;
  }
  addIcons(map);
}
`;
writeFileSync(join(root, "src/app/icons.ts"), out);
console.log(`icons.ts: ${names.length} names`);
