# Technoplatz BI - Action
# Mustafa Mat @Technoplatz 2019-2023
name: Deploy API image to Github Packages
on:
  push:
    branches:
      - dev0
    paths:
      - "api/**"
      - ".github/workflows/push-api-to-packages.yml"
      - ".dev.env"
  pull_request:
    branches:
      - main
    paths:
      - "api/**"
env:
  API_IMAGE_NAME: bi-api
  API_FOLDER: api
  DOCKERFILE: Dockerfile
  VERSION: latest
jobs:
  push-to-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build API image
        id: build-api-image
        run: |
          IMAGE_NAME=$API_IMAGE_NAME
          ref_=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          if [ $ref_ != "main" ]; then IMAGE_NAME=$IMAGE_NAME-$ref_; fi
          cd $API_FOLDER
          docker build . --file $DOCKERFILE --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
          echo "::set-output name=imagename::$(echo $IMAGE_NAME)"
      - name: Log in to Github registry
        run: |
          echo "${{ secrets.ACCESS_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push API image
        id: push-api-image
        run: |
          IMAGE_NAME=${{steps.build-api-image.outputs.imagename}}
          IMAGE_ID=ghcr.io/technoplatz/$IMAGE_NAME:$VERSION
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
      - name: Logout from Github
        run: |
          docker logout ghcr.io
