name: Action for test
on:
  push:
    branches:
      - dev0
env:
  PWA_VERSION: latest
jobs:
  deneme:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Echo system variables
        run: |
          echo "github.repository: ${{ github.repository }}"
          echo "github.repository_owner: ${{ github.repository_owner }}"
          echo "github.ref: ${{ github.ref }}"
          ref_=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo "ref_: $ref_"
          IMAGE_ID_ = "bi-api"
          PREFIX=""
          if ($ref_ != "main") {
            IMAGE_ID_ = $IMAGE_ID_-$ref_
          }
          echo "IMAGE_ID_: $IMAGE_ID_"